# Generated by Django 6.0.3 on 2026-03-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='建仓基准价')),
                ('total_funds', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12, verbose_name='总资金(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格交易计划',
                'verbose_name_plural': '网格交易计划',
                'db_table': 'grid_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GridRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_index', models.IntegerField(verbose_name='档位编号')),
                ('target_buy_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='计划买入价')),
                ('target_sell_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='计划卖出价')),
                ('volume', models.IntegerField(verbose_name='买入股数(100的整数倍)')),
                ('actual_buy_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='实际买入价')),
                ('buy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='买入金额')),
                ('buy_time', models.DateTimeField(blank=True, null=True, verbose_name='买入时间')),
                ('actual_sell_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='实际卖出价')),
                ('sell_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='卖出金额')),
                ('sell_time', models.DateTimeField(blank=True, null=True, verbose_name='卖出时间')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='收益(元)')),
                ('status', models.CharField(choices=[('PENDING', '待买入'), ('HOLDING', '持仓中'), ('CLEARED', '已清仓')], default='PENDING', max_length=10, verbose_name='状态')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='trader.gridplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '网格交易记录',
                'verbose_name_plural': '网格交易记录',
                'db_table': 'grid_record',
                'ordering': ['part_index'],
                'unique_together': {('plan', 'part_index')},
            },
        ),
    ]
