# Generated by Django 4.2.29 on 2026-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_gridplan_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridplan',
            name='grid_ratio',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=6, verbose_name='网格大小'),
        ),
    ]
