# Generated by Django 4.2.29 on 2026-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_gridplan_grid_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridplan',
            name='part_count',
            field=models.IntegerField(default=5, verbose_name='网格档数'),
        ),
    ]
