# Generated by Django 4.2.29 on 2026-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_gridplan_part_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
