# Generated by Django 4.2.29 on 2026-03-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_gridplan_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gridrecord',
            options={'ordering': ['part_index', '-id'], 'verbose_name': '网格交易记录', 'verbose_name_plural': '网格交易记录'},
        ),
        migrations.AlterUniqueTogether(
            name='gridrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gridrecord',
            name='is_active_cycle',
            field=models.BooleanField(default=True, verbose_name='当前循环'),
        ),
    ]
