# Generated by Django 4.2.29 on 2026-03-26 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0006_alter_gridrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '自选股',
                'verbose_name_plural': '自选股',
                'db_table': 'stock_watchlist',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'stock_code')},
            },
        ),
    ]
