# Generated by Django 4.2.29 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_stockwatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wechat_webhook',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='企业微信机器人地址'),
        ),
    ]
