# Generated by Django 4.2.29 on 2026-05-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0008_userprofile_wechat_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('target_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='告警价格')),
                ('condition', models.CharField(choices=[('above', '高于'), ('below', '低于')], default='below', max_length=10, verbose_name='告警条件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_monitors', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '股价监控',
                'verbose_name_plural': '股价监控',
                'db_table': 'stock_price_monitor',
                'ordering': ['-created_at'],
            },
        ),
    ]
